# Generated by Django 3.0.2 on 2020-08-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('artists', models.CharField(max_length=999)),
                ('date', models.DateField(blank=True)),
                ('yt_url', models.CharField(blank=True, max_length=999)),
                ('sc_url', models.CharField(blank=True, max_length=999)),
                ('sp_url', models.CharField(blank=True, max_length=999)),
                ('it_url', models.CharField(blank=True, max_length=999)),
            ],
        ),
    ]
