# Generated by Django 3.0.2 on 2020-08-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='artists',
        ),
    ]
