# Generated by Django 3.0.2 on 2020-08-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0003_auto_20200825_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='release',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
