# Generated by Django 3.0.2 on 2020-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_auto_20200825_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='yt_embed',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
