# Generated by Django 3.0.2 on 2020-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_release_yt_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='random_str',
            field=models.CharField(default=0, max_length=999),
        ),
    ]
