# Generated by Django 3.0.2 on 2020-08-26 11:46

from django.db import migrations, models
import releases.models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_release_random_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='random_str',
            field=models.CharField(default=releases.models.id_generator, max_length=999),
        ),
    ]
