# Generated by Django 3.0.2 on 2020-08-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_random_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='random_str',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
