# Generated by Django 3.0.2 on 2020-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200825_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='markup_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
