# Generated by Django 3.0.2 on 2020-08-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_markup_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='markup_percentage',
            field=models.FloatField(default=1.2),
        ),
    ]
