# Generated by Django 3.0.2 on 2020-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200825_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='markup_percentage',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
