# Generated by Django 3.0.2 on 2020-08-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200825_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
