# Generated by Django 3.0.2 on 2020-08-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, unique=True)),
                ('email', models.CharField(blank=True, max_length=999)),
                ('description', models.TextField(blank=True)),
                ('front_page_priority', models.IntegerField(default=10)),
                ('front_page_img', models.ImageField(null=True, upload_to='')),
                ('artist_page_img', models.ImageField(null=True, upload_to='')),
                ('artist_page_bg', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
