# Generated by Django 3.0.2 on 2020-08-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='real_name',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
