# Generated by Django 3.0.2 on 2020-08-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_real_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='front_page_priority',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
