# Generated by Django 3.0.2 on 2020-08-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20200825_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='fb_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='artist',
            name='ig_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='artist',
            name='it_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='artist',
            name='sc_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='artist',
            name='sp_url',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AddField(
            model_name='artist',
            name='yt_url',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
