# Generated by Django 3.0.2 on 2020-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20200825_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_page_font_color',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
