# Generated by Django 3.0.2 on 2020-08-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_artist_page_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_page_shadow',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
