# Generated by Django 3.0.2 on 2020-09-21 16:18

from django.db import migrations, models
import scrape.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20200921_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='random_str',
            field=models.CharField(default=scrape.models.id_generator, max_length=999),
        ),
        migrations.AddField(
            model_name='video',
            name='random_str',
            field=models.CharField(default=scrape.models.id_generator, max_length=999),
        ),
        migrations.AddField(
            model_name='video_history',
            name='random_str',
            field=models.CharField(default=scrape.models.id_generator, max_length=999),
        ),
    ]
